coursemanaging/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from . import views

app_name = "coursemanaging"
urlpatterns = [
    url(r'^$', views.LandingView.as_view(),
        name='landing'),
    url(r'^course/register$', login_required(views.CourseCreateView.as_view()),
        name='course-create'),
    url(r'^course/(?P<pk>[0-9]+)/$', views.CourseDetailView.as_view(),
        name='course-detail'),
    url(r'^activities/$', views.Activities.as_view(),
        name='activities'),
    url(r'^course/update/(?P<pk>[0-9]+)/$', login_required(views.CourseUpdateView.as_view()),
        name='course-update'),
    url(r'^courses$', login_required(views.CoursesUserListView.as_view()),
        name='courses-user'),
    url(r'^course/(?P<pk>[0-9]+)/session-create$', login_required(views.SessionCreateView.as_view()),
        name='session-create'),
    url(r'^course/(?P<pk>[0-9]+)/session-user-list', login_required(views.SessionUserListView.as_view()),
        name='session-user-list'),
    url(r'^session/(?P<pk>[0-9]+)/session-update$', login_required(views.SessionUpdateView.as_view()),
        name='session-update'),
    url(r'^event/create$', login_required(views.EventCreateview.as_view()),
        name='event-create'),
    url(r'^event/(?P<pk>[0-9]+)/update$', login_required(views.EventUpdateView.as_view()),
        name='event-update'),
    url(r'^event/(?P<pk>[0-9]+)/delete', login_required(views.EventDeleteView.as_view()),
        name='event-delete'),
    url(r'^event/(?P<pk>[0-9]+)$', views.EventDetailView.as_view(),
        name='event-detail'),
    url(r'^building-day/create$', login_required(views.BuildingDayCreateview.as_view()),
        name='building-day-create'),
    url(r'^building-day/(?P<pk>[0-9]+)/building-day-update$', login_required(views.BuildingDayUpdateView.as_view()),
        name='building-day-update'),
    url(r'^building-day/(?P<pk>[0-9]+)/building-day-delete', login_required(views.BuildingDayDeleteView.as_view()),
        name='building-day-delete'),
    url(r'^building-day/(?P<pk>[0-9]+)$', login_required(views.BuildingDayDetailView.as_view()),
        name='building-day-detail'),
    url(r'^register/$', views.RegisterView.as_view(),
        name='user-register'),
    url(r'^user/$', login_required(views.UserDetailView.as_view()),
        name='user-detail'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
        name='user-activate'),
    url(r'^login/$', auth_views.login, {'template_name': 'coursemanaging/user-login.html'},
        name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'},
        name='logout'),
    url('^account-activation-sent', views.AccountActivationSentView.as_view(),
        name='account-activation-sent'),
    url(r'^calendar/', views.CalendarView.as_view(),
        name='calendar'),
    url(r'^blog/$', views.NewsView.as_view(),
        name='news'),
    url(r'^blog/(?P<pk>[0-9]+)$', views.NewsView.as_view(),
        name='news'),
    url(r'^impossible/$', views.ImpossibleView.as_view(),
        name='impossible'),
    url(r'^thanks/$', views.ThanksView.as_view(),
        name='thanks'),

    url(r'^ajax-calendar/$', views.get_calendar,
        name='ajax-calendar'),
    url(r'^ajax-week-calendar/$', views.get_week_calendar,
        name='ajax-calendar'),
]

mostaardimgur/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = "mostaardimgur"

urlpatterns = [
    url(r'^callback', views.CallBackView.as_view()),
    url(r'^catchtoken/$', views.catchtoken,
        name='catchtoken'),
    url(r'^albums/(?P<pk>[0-9]+)$', views.AlbumDetailView.as_view(),
        name='album-detail'),
    url(r'^albums/$', views.AlbumListView.as_view(),
        name='album-list'),
    url(r'^imgur-authorize/$', login_required(views.AuthorizeRedirectView.as_view()),
        name="authorize"),


]

opengym/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

app_name = "opengym"
urlpatterns = [
    url(r'^', include('coursemanaging.urls')),
    url(r'^', include('mostaardimgur.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opengym/templates/base.html
<!DOCTYPE html>
<html lang="nl">
<head>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'opengym/style.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Julius+Sans+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.2.1.js"
            integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
            integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
            crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/9d1627fd30.js"></script>
    <script src="{% static 'opengym/opengym.js' %}"></script>
    {% block extra_head %}

    {% endblock %}
    <meta charset="UTF-8">
    <title>Open Gym - DIY Sports infrastructure {% block page-title %}{% endblock %}</title>
    <meta name="description" content=" DIY Sports Infrastructure Sportconstructies uit herbruikte materialen. Door sporters, voor iedereen. Op ons sportpark onder de E314-brug te Wilsele kan je 24/7 boulderen, krachttrainen, slacklinen, etc..">
    <meta name="keywords" content="Leuven, open, gym, fitness, diy, bouw, sport, infrastructure, infrastructuur, wilsele, 24/24, 7/7, park, iedereen">
</head>
<body onload="{% block onload %}
{% endblock %}">
<nav class="navbar navbar-expand-md fixed-top">
    <div class="social-media-buttons">
        <a href="https://www.facebook.com/OpenGymLeuven/" class="fa fa-facebook"></a>
        <a href="https://www.youtube.com/channel/UCJ2U_COkpoFe0Nn0noNzLGw" class="fa fa-youtube"></a>
    </div>
    <a class="navbar-brand ml-3" href="{% url 'coursemanaging:landing' %}"> Open Gym</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">KOEKSKES</span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-collapse justify-content-md-center">
            <li>
                {% if current_page == 'courses' %}
                    <a class="nav-link" href="{% url 'coursemanaging:activities' %}">
                        <span class="fa fa-angle-double-right" aria-hidden="true"></span>
                        Activiteiten
                        <span class="fa fa-angle-double-left" aria-hidden="true"></span>
                    </a>
                {% else %}
                    <a class="nav-link" href="{% url 'coursemanaging:activities' %}">
                        Activiteiten
                    </a>
                {% endif %}

            </li>
            <li>
                {% if current_page == 'news' %}
                    <a class="nav-link" href="{% url 'coursemanaging:news' %}">
                        <span class="fa fa-angle-double-right" aria-hidden="true"></span>
                        Nieuws
                        <span class="fa fa-angle-double-left" aria-hidden="true"></span>
                    </a>

                {% else %}
                    <a class="nav-link" href="{% url 'coursemanaging:news' %}">Nieuws</a>
                {% endif %}

            </li>
            <li>
                {% if current_page == 'calendar' %}
                    <a class="nav-link" href="{% url 'coursemanaging:calendar' %}">
                        <span class="fa fa-angle-double-right" aria-hidden="true"></span>
                        Open Agenda
                        <span class="fa fa-angle-double-left" aria-hidden="true"></span>
                    </a>

                {% else %}
                    <a class="nav-link" href="{% url 'coursemanaging:calendar' %}">Open Agenda</a>
                {% endif %}
            </li>
            <li>
                {% if current_page == 'album' %}
                    <a class="nav-link" href="{% url 'mostaardimgur:album-list' %}">
                        <span class="fa fa-angle-double-right" aria-hidden="true"></span>
                        Album
                        <span class="fa fa-angle-double-left" aria-hidden="true"></span>
                    </a>

                {% else %}
                    <a class="nav-link" href="{% url 'mostaardimgur:album-list' %}">Album</a>
                {% endif %}
            </li>

        </ul>
        <ul class="nav navbar-nav navbar-right mr-5">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle btn-lg" id="dropdown01" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">{{ user.first_name }}</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="{% url 'coursemanaging:courses-user' %}">Mijn lessen</a>
                        <a class="dropdown-item" href="{% url 'coursemanaging:user-detail' %}">Mijn gegevens</a>
                        <a class="dropdown-item" href="{% url 'coursemanaging:logout' %}">Logout</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle btn-lg" id="dropdown02" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">Login</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown02">
                        <a class="dropdown-item" href="{% url 'coursemanaging:login' %}">Login</a>
                        <a class="dropdown-item" href="{% url 'coursemanaging:user-register' %}">Register</a>
                    </div>
                </li>
            {% endif %}
        </ul>
    </div>
    {% block extra-nav %}
    {% endblock %}
</nav>

<div class="base container">
    {% block content %}
    {% endblock %}
</div>
{% block content-no-div %}
{% endblock %}
</body>
</html>