coursemanaging/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from . import views

app_name = "coursemanaging"
urlpatterns = [
    url(r'^$', views.LandingView.as_view(),
        name='landing'),
    url(r'^course/register$', login_required(views.CourseCreateView.as_view()),
        name='course-create'),
    url(r'^course/(?P<pk>[0-9]+)/$', views.CourseDetailView.as_view(),
        name='course-detail'),
    url(r'^activities/$', views.Activities.as_view(),
        name='activities'),
    url(r'^course/update/(?P<pk>[0-9]+)/$', login_required(views.CourseUpdateView.as_view()),
        name='course-update'),
    url(r'^courses$', login_required(views.CoursesUserListView.as_view()),
        name='courses-user'),
    url(r'^course/(?P<pk>[0-9]+)/session-create$', login_required(views.SessionCreateView.as_view()),
        name='session-create'),
    url(r'^course/(?P<pk>[0-9]+)/session-user-list', login_required(views.SessionUserListView.as_view()),
        name='session-user-list'),
    url(r'^session/(?P<pk>[0-9]+)/session-update$', login_required(views.SessionUpdateView.as_view()),
        name='session-update'),
    url(r'^event/create$', login_required(views.EventCreateview.as_view()),
        name='event-create'),
    url(r'^event/(?P<pk>[0-9]+)/update$', login_required(views.EventUpdateView.as_view()),
        name='event-update'),
    url(r'^event/(?P<pk>[0-9]+)/delete', login_required(views.EventDeleteView.as_view()),
        name='event-delete'),
    url(r'^event/(?P<pk>[0-9]+)$', views.EventDetailView.as_view(),
        name='event-detail'),
    url(r'^building-day/create$', login_required(views.BuildingDayCreateview.as_view()),
        name='building-day-create'),
    url(r'^building-day/(?P<pk>[0-9]+)/building-day-update$', login_required(views.BuildingDayUpdateView.as_view()),
        name='building-day-update'),
    url(r'^building-day/(?P<pk>[0-9]+)/building-day-delete', login_required(views.BuildingDayDeleteView.as_view()),
        name='building-day-delete'),
    url(r'^building-day/(?P<pk>[0-9]+)$', login_required(views.BuildingDayDetailView.as_view()),
        name='building-day-detail'),
    url(r'^register/$', views.RegisterView.as_view(),
        name='user-register'),
    url(r'^user/$', login_required(views.UserDetailView.as_view()),
        name='user-detail'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
        name='user-activate'),
    url(r'^login/$', auth_views.login, {'template_name': 'coursemanaging/user-login.html'},
        name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'},
        name='logout'),
    url('^account-activation-sent', views.AccountActivationSentView.as_view(),
        name='account-activation-sent'),
    url(r'^calendar/', views.CalendarView.as_view(),
        name='calendar'),
    url(r'^blog/$', views.NewsView.as_view(),
        name='news'),
    url(r'^blog/(?P<pk>[0-9]+)$', views.NewsView.as_view(),
        name='news'),
    url(r'^impossible/$', views.ImpossibleView.as_view(),
        name='impossible'),
    url(r'^thanks/$', views.ThanksView.as_view(),
        name='thanks'),

    url(r'^ajax-calendar/$', views.get_calendar,
        name='ajax-calendar'),
    url(r'^ajax-week-calendar/$', views.get_week_calendar,
        name='ajax-calendar'),
]

opengym/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

app_name = "opengym"
urlpatterns = [
    url(r'^', include('coursemanaging.urls')),
    url(r'^', include('mostaardimgur.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coursemanaging/models.py
from datetime import date
from datetime import timedelta

from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext as _
from markdown import markdown


class MyUserManager(BaseUserManager):
    """
    A custom user manager to deal with emails as unique identifiers for auth
    instead of usernames. The default that's used is "UserManager"
    """

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('birthdate', date.today())

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    SEX_CHOICES = (
        ('F', 'Female',),
        ('M', 'Male',),
        ('U', 'Unsure',),
    )

    email = models.EmailField(unique=True, null=True)
    first_name = models.CharField(_('first name'), max_length=30)
    last_name = models.CharField(_('last name'), max_length=30)
    birthdate = models.DateField()
    teacher = models.BooleanField(default=False)
    email_confirmed = models.BooleanField(default=False)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(default=timezone.now, verbose_name='date joined', null=True)

    USERNAME_FIELD = 'email'
    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)


class Course(models.Model):
    BEGINNER = 1
    INTERMEDIATE = 2
    ADVANCED = 3

    LEVEL_CHOICES = ((BEGINNER, 'Beginner'),
                     (INTERMEDIATE, 'Intermediate'),
                     (ADVANCED, 'Advanced'),
                     )

    course_name = models.CharField(max_length=100, null=False, blank=False)
    course_level = models.SmallIntegerField(null=False, blank=False, choices=LEVEL_CHOICES)
    build_up_sessions = models.BooleanField(default=False)
    max_students_session = models.PositiveSmallIntegerField(null=True, blank=True)
    max_students_course = models.PositiveSmallIntegerField(null=True, blank=True)
    description = models.TextField()
    location_short = models.CharField(max_length=30, null=True, blank=True)
    location_street = models.CharField(max_length=50, null=True, blank=True)
    location_number = models.CharField(max_length=5, null=True, blank=True)
    location_city = models.CharField(max_length=50, null=True, blank=True)
    is_active = models.BooleanField(default=True)

    teachers = models.ManyToManyField(User, related_name='courses_teacher', blank=True)
    students = models.ManyToManyField(User, related_name='courses_student', blank=True)

    def __str__(self):
        return self.course_name

    def is_full(self):
        if self.max_students_course:
            return self.max_students_course <= self.students.count()
        return False

    def get_next_session(self):
        if Session.objects.filter(course=self, start__gte=timezone.now()).exists():
            return Session.objects.filter(course=self, start__gte=timezone.now()).order_by('start')[0]
        else:
            return None

    def get_future_sessions(self):
        return Session.objects.filter(start__gte=timezone.now(), course=self).order_by('start')

    def user_is_subscribed(self, user):
        return self.students.filter(id=user.id).exists()

    def user_is_teacher(self, user):
        return self.teachers.filter(id=user.id).exists()

    def subscribe_user(self, user):
        if self.max_students_course and self.students.count() >= self.max_students_course:
            raise ValidationError(
                "This course is full",
                code='full',
            )
        self.students.add(user)

    def unsubscribe_user(self, user):
        if user not in self.students.all():
            raise ValidationError(
                "User not in session ",
                code='not found',
            )
        self.students.remove(user)

    def clean(self):
        if self.max_students_course and self.students.count() > self.max_students_course:
            raise ValidationError(
                "This course has more students than possible",
                code='full',
            )

    def save(self, *args, **kwargs):
        self.full_clean()
        super(Course, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('coursemanaging:course-detail', args=[self.id])


class Event(models.Model):
    start = models.DateTimeField(null=False, blank=False)
    duration = models.DurationField(null=False, blank=False, default=timedelta())
    facebook_event_url = models.URLField(null=True, blank=True)
    event_name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)

    def get_calendar_url(self):
        return self.get_absolute_url()

    def get_absolute_url(self):
        return reverse_lazy('coursemanaging:event-detail', args=[self.id])

    def get_entry_title(self):
        return self.event_name

    def get_end(self):
        return self.start + self.duration

    def __str__(self):
        return self.event_name


class BuildingDay(models.Model):
    start = models.DateTimeField(null=False, blank=False)
    duration = models.DurationField(null=False, blank=False, default=timedelta())
    description = models.TextField()
    responsible_users = models.ManyToManyField(User, related_name='building_responsibilitites', blank=True)
    subscribed_users = models.ManyToManyField(User, related_name='building_days', blank=True)

    def user_is_subscribed(self, user):
        return self.subscribed_users.filter(id=user.id).exists()

    def subscribe_user(self, user):
        if not self.user_is_subscribed(user):
            self.subscribed_users.add(user)
            self.save()

    def get_absolute_url(self):
        return reverse_lazy('coursemanaging:building-day-detail', args=[self.id])

    def get_end(self):
        return self.start + self.duration

    def __str__(self):
        return 'bouwdag op ' + str(self.start)


class Session(models.Model):
    start = models.DateTimeField(null=False, blank=False)
    duration = models.DurationField(null=False, blank=False, default=timedelta())
    extra_info = models.TextField(null=True, blank=True)
    max_students_diff_course = models.BooleanField(default=False)
    max_students = models.PositiveSmallIntegerField(null=True, blank=True)
    location_diff_course = models.BooleanField(default=False)
    location_short = models.CharField(max_length=30, null=True, blank=True)
    location_street = models.CharField(max_length=50, null=True, blank=True)
    location_number = models.CharField(max_length=5, null=True, blank=True)
    location_city = models.CharField(max_length=50, null=True, blank=True)

    course = models.ForeignKey(Course, related_name='sessions', default=1, blank=True)
    subscribed_users = models.ManyToManyField(User, related_name='sessions', blank=True)

    class Meta:
        ordering = ["start"]

    def extra_info_rendered(self):
        return markdown(self.extra_info)

    def user_is_subscribed(self, user):
        return self.subscribed_users.filter(id=user.id).exists()

    def time_until(self):
        return self.start - timezone.now()

    def subscribe_user(self, user):
        if self.max_students and self.subscribed_users.count() >= self.max_students:
            raise ValidationError(
                "This session is full",
                code='full',
            )
        self.subscribed_users.add(user)

    def unsubscribe_user(self, user):
        if user not in self.subscribed_users.all():
            raise ValidationError(
                "User not in session ",
                code='not found',
            )
        self.subscribed_users.remove(user)

    def get_location_short(self):
        if self.location_diff_course:
            return self.location_short
        else:
            return self.course.location_short

    def get_location_street(self):
        if self.location_diff_course:
            return self.location_street
        else:
            return self.course.location_street

    def get_location_number(self):
        if self.location_diff_course:
            return self.location_number
        else:
            return self.course.location_number

coursemanaging/templates/coursemanaging/account-activation-invalid.html
{% extends "base.html" %}
{% block content %}
<h3>Email is invalid</h3>
{% endblock %}

coursemanaging/templates/coursemanaging/account-activation-sent.html
{% extends "base.html" %}
{% block content %}
<h1>Mail was sent succesfully, check your mailbox</h1>
{% endblock %}

coursemanaging/templates/coursemanaging/building-day-detail.html
{% extends "base.html" %}
{% load coursemanaging_extras %}
{% block content %}
    <div class="open-gym-page text-center">
        {% if user.is_staff %}
            <div class="row mb-5">
                <div class="col-6 text-center"><a class="btn btn-warning"
                                                  href="{% url 'coursemanaging:building-day-update' buildingday.id %}"> <span
                        class="fa fa-refresh" aria-hidden="true"></span> Update </a>
                </div>
                <div class="col-6 text-center"><a class="btn btn-danger"
                                                  href="{% url 'coursemanaging:building-day-delete' buildingday.id %}"> <span
                        class="fa fa-times" aria-hidden="true"></span> Verwijder</a>
                </div>
            </div>
        {% endif %}
        <h1 class=>Open Gym gaat bouwen op {{ buildingday.start|date:'d/m/o' }}</h1>
        <h2 class=""> meer info bij
            {% for user in buildingday.responsible_users.all %}{{ user.first_name }} {% endfor %}</h2>
        {% autoescape off %}
            <p class="text-center mt-5">{{ buildingday.description }}</p>
        {% endautoescape %}
        {% if not user_is_subscribed %}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="subscribe" value="true">
                <button type="submit" class="og-btn btn btn-primary">Mee bouwen!</button>
            </form>
        {% else %}
            <button type="button" class="og-btn btn btn-primary" disabled>Bedankt!</button>
        {% endif %}


    </div>
{% endblock %}

coursemanaging/templates/coursemanaging/calendar-ajax.html
{{calendar}}

coursemanaging/templates/coursemanaging/course-detail.html
{% extends "base.html" %}
{% load coursemanaging_extras %}
{% block content %}
    <h1 class="text-center">{{ course.course_name }}</h1>


    <ul class="nav nav-tabs opengym-tabs-head" id="courseTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link tab" id="information-tab" data-toggle="tab" href="#information" role="tab"
               aria-controls="information"
               aria-selected="true">Informatie</a>
        </li>
        <li class="nav-item">
            <a class="nav-link tab active" id="sessions-tab" data-toggle="tab" href="#sessions" role="tab"
               aria-controls="sessions"
               aria-selected="true">Sessies</a>
        </li>
        <li class="nav-item">
            <a class="nav-link tab" id="teachers-tab" data-toggle="tab" href="#teachers" role="tab"
               aria-controls="teachers"
               aria-selected="true">Leerkrachten</a>
        </li>
        {% if is_teacher %}
            <li class="nav-item">
                <a class="nav-link tab" id="students-tab" data-toggle="tab" href="#students" role="tab"
                   aria-controls="students"
                   aria-selected="true">Studenten</a>
            </li>
        {% endif %}
    </ul>

    <div class="tab-content pt-5 opengym-tab" id="courseTabContent">
        <!-- start information tab -->
        <div class="tab-pane fade " id="information" role="tabpanel" aria-labelledby="information-tab">
            <table class="table">
                <tbody>
                <tr>
                    <th scope="row">Niveau</th>
                    <td>{{ course.get_course_level_display }}</td>
                </tr>
                <tr>
                    <th scope="row">Opbouwende sessies <span data-toggle="tooltip" class="click-hover"
                                                             data-placement="top"
                                                             title="Dit betekent dat elke les verder gaat op vorige sessies, wat het moeilijker maakt lessen te missen">
                (?)
            </span></th>
                    <td>
                        {{ course.build_up_sessions|yesno:"Ja,nee" }}
                    </td>
                </tr>
                {% if course.max_students_course %}
                    <tr>
                        <th scope="row">Max inschrijvingen</th>
                        <td>{{ course.max_students_course }}</td>
                    </tr>
                {% endif %}
                {% if is_student %}
                    <tr>
                        <th scope="row">Aantal inschrijvingen</th>
                        <td>{{ course.students.count }}</td>
                    </tr>
                {% endif %}
                <tr>
                    <th scope="row">Beschrijving</th>
                    <td>{{ course.description }}</td>
                </tr>
                <tr>
                    <th scope="row">Locatie</th>
                    <td>{{ course.location_short|default_if_none:"" }}</td>
                </tr>
                {% if course.location_city %}
                    <tr>
                        <th scope="row">Stad</th>
                        <td>{{ course.location_city|default_if_none:"" }}</td>
                    </tr>
                {% endif %}
                {% if course.location_street %}
                    <tr>
                        <th scope="row">Straat</th>
                        <td>{{ course.location_street|default_if_none:"" }}</td>
                    </tr>
                {% endif %}
                {% if course.location_number %}
                    <tr>
                        <th scope="row">Huisnr</th>
                        <td>{{ course.location_number|default_if_none:"" }}</td>
                    </tr>
                {% endif %}
                <tr>
                    <th scope="row">Inschrijven</th>
                    <td>
                        {% if not is_teacher and not is_student %}
                            {% if not course.is_full %}
                                <form method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="join_course" value="true">
                                    <button type="submit" class="btn btn-primary">Schrijf je in</button>
                                </form>
                            {% else %}
                                <button class="btn btn-primary disabled">Volzet</button>
                            {% endif %}
                        {% elif is_teacher %}
                            <button class="btn btn-success disabled">U bent leerkracht</button>
                        {% else %}
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="leave_course" value="true">
                                <button type="submit" class="btn btn-primary">Uitschrijven</button>
                            </form>
                        {% endif %}
                    </td>
                </tr>
                {% if is_teacher %}
                    <tr>
                        <th scope="row">Updaten</th>
                        <td><a class="btn btn-warning " href="{% url 'coursemanaging:course-update' course.id %}"><span
                                class="fa fa-refresh" aria-hidden="true"></span></a></td>
                    </tr>
                {% endif %}


                </tbody>
            </table>
        </div>
        <!-- end information tab -->
        <!-- start sessions tab -->
        <div class="tab-pane fade active show" id="sessions" role="tabpanel" aria-labelledby="sessions-tab">
            {% if course.get_future_sessions %}
                <table class="table">
                    <thead>
                    <tr>
                        <th>Tijdstip</th>
                        <th>Duur</th>
                        <th>Locatie <span data-toggle="tooltip" class="click-hover"
                                          data-placement="top"
                                          title="Enkel van toepassing als de sessie op een andere locatie doorgaat dan beschreven op het informatie tabblad">(?)</span>
                        </th>
                        <th>Max deelnemers</th>
                        <th>Extra info</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for session in course.get_future_sessions %}
                        <tr>
                            <td id="time-{{ session.id }}">{{ session.start }}</td>
                            <td>{{ session.duration }}</td>
                            <td>
                                {% if session.location_diff_course %}
                                    <address>
                                        {{ session.location_short|default_if_none:"" }}<br>
                                        {{ session.location_street|default_if_none:"" }}
                                        {{ session.location_number|default_if_none:"" }}<br>
                                        {{ session.location_city|default_if_none:"" }}<br>

                                    </address>
                                {% endif %}
                            </td>
                            <td>
                                {{ session.get_max_students|default_if_none:"geen maximum" }}
                            </td>
                            <td>
                                {{ session.extra_info_rendered|safe|default_if_none:"geen maximum" }}
                            </td>
                            <td>
                                {% if is_teacher %}
                                    <a href="{% url 'coursemanaging:session-user-list' session.id %}">{{ session.subscribed_users.all.count }}
                                        inschrijving(en)</a>
                                {% else %}
                                    {% if not sessions_subscribed|get_item:session.id %}
                                        {% if not session.is_full %}
                                            <form method="post">
                                                {% csrf_token %}
                                                <input type="hidden" name="join_session" value="{{ session.id }}">
                                                <button type="submit" class="btn btn-primary">Schrijf je in</button>
                                            </form>
                                        {% else %}
                                            <button class="btn btn-primary disabled">Volzet</button>
                                        {% endif %}
                                    {% else %}
                                        <form method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="leave_session" value="{{ session.id }}">
                                            <button type="submit" class="btn btn-primary">Uitschrijven</button>
                                        </form>
                                    {% endif %}
                                {% endif %}
                            </td>
                            <td>
                                {% if is_teacher %}
                                    <a class="btn btn-warning "
                                       href="{% url 'coursemanaging:session-update' session.id %}"><span
                                            class="fa fa-refresh" aria-hidden="true"></span></a>
                                {% endif %}
                            </td>
                            <td>
                                {% if is_teacher %}
                                    <button id="{{ session.id }}" class="btn btn-danger available remove-session"
                                            data-toggle="modal"
                                            data-target="#remove-modal"><span
                                            class="fa fa-times" aria-hidden="true"></span>
                                    </button>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <H3 class="ml-4"><span class="fa fa-frown-o mr-3" aria-hidden="true"></span> Er zijn momenteel geen
                    sessies gepland</H3>
            {% endif %}
            {% if is_teacher %}
                <a href="{% url 'coursemanaging:session-create' course.id %}"
                   class="btn btn-success mt-5">
                    <span class="fa fa-plus" aria-hidden="true"></span> Sessie(s) toevoegen
                </a>
            {% endif %}
        </div>
        <!-- end sessions tab -->
        <!-- start teachers tab -->
        <div class="tab-pane fade " id="teachers" role="tabpanel" aria-labelledby="teachers-tab">
            <table class="table">
                <thead>
                <tr>
                    <th>Voornaam</th>
                    <th>Naam</th>
                    <th>Email</th>
                </tr>
                </thead>
                <tbody>
                {% for user in course.teachers.all %}
                    <tr>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.last_name }}</td>
                        <td>{{ user.email }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- end teachers tab -->
        <!-- start students tab -->
        <div class="tab-pane fade " id="students" role="tabpanel" aria-labelledby="students-tab">
            <table class="table">
                <thead>
                <tr>
                    <th>Voornaam</th>
                    <th>Naam</th>
                </tr>
                </thead>
                <tbody>
                {% for user in course.students.all %}
                    <tr>
                        <td> {{ user.first_name }}</td>
                        <td>{{ user.last_name }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <!-- end students tab -->
    </div>
    <div class="modal fade" id="remove-modal" role="dialog">
        <div class="modal-dialog modal-lg">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Sessie verwijderen</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Bent u zeker dat u de sessie op <span id="remove-help"></span> wilt verwijderen?</p>
                    <div class="modal-footer">
                        <div>
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" id="remove-session" name="remove_session" value="">
                                <button type="submit" class="btn btn-danger">Verwijder</button>
                            </form>
                        </div>
                        <div>
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Neejneejneej
                            </button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

coursemanaging/templates/coursemanaging/event-detail.html
{% extends "base.html" %}
{% load coursemanaging_extras %}
{% block content %}
    <div class="open-gym-page text-center">
        {% if user.is_staff %}
            <div class="row mb-5">
                <div class="col-6 text-center"><a class="btn btn-warning"
                                                  href="{% url 'coursemanaging:event-update' event.id %}"> <span
                        class="fa fa-refresh" aria-hidden="true"></span> Update </a>
                </div>
                <div class="col-6 text-center"><a class="btn btn-danger"
                                                  href="{% url 'coursemanaging:event-delete' event.id %}"> <span
                        class="fa fa-times" aria-hidden="true"></span> Verwijder</a>
                </div>
            </div>
        {% endif %}
        <h1 class="">{{ event.event_name }}  <small>(<a class="fa fa-facebook" href="{{ event.facebook_event_url }}"></a>)</small></h1>
        <h2 class=""> {{ event.start|date:'d/m/o H:i' }} tot {{ event.get_end|date:'d/m/o H:i' }} </h2>
        {% if event.facebook_event_url %}
        {% endif %}
        {% if event.facebook_event_url %}
            <p class="mt-5">
                {{ event.description|default_if_none:'' }}
            </p>
        {% endif %}

    </div>
{% endblock %}